<?php require_once APPROOT . '/views/inc/header.php'; ?>
<?php 
$backUrl = URLROOT . '/Service/profile';
require_once APPROOT . '/views/inc/components/taskbar/taskbar_back.php'; ?>
<link rel="stylesheet" href="<?php echo URLROOT; ?>/css/components/servicesP/s_availability.css">
<div class="container">
    <header class="main">
        <h2 class="main">Manage your available dates</h2>
        
    </header>

    <div class="tabs">
        <div class="tab active" data-tab="calendar">Calendar View</div>
        <div class="tab" data-tab="availability">Availability List</div>
    </div>

    <div class="tab-content active" id="calendar-tab">
        <div class="grid-2">
            <!-- Calendar -->
            <article class="card">
                <header class="card__head">
                    <h2 class="card__title">Available Days</h2>
                </header>
                <div class="card__body">
                    <div class="cal">
                        <div class="cal__header">
                            <div class="cal__month">September 2025</div>
                            <div class="cal__nav">
                                <button class="cal__nav-btn" id="prev-month">←</button>
                                <button class="cal__nav-btn" id="next-month">→</button>
                            </div>
                        </div>

                        <div class="cal__dow">
                            <div>Sun</div><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div>
                        </div>

                        <div class="cal__grid" id="calendar-grid">
                            <!-- Calendar days will be generated by JavaScript -->
                        </div>
                        
                        <div class="legend">
                            <div class="legend-item">
                                <div class="legend-color legend-available"></div>
                                <span>Available</span>
                            </div>
                            <div class="legend-item">
                                <div class="legend-color legend-booked"></div>
                                <span>Booked</span>
                            </div>
                            <div class="legend-item">
                                <div class="legend-color legend-unavailable"></div>
                                <span>Unavailable</span>
                            </div>
                            <div class="legend-item">
                                <div class="legend-color legend-today"></div>
                                <span>Today</span>
                            </div>
                            <div class="legend-item">
                                <div class="legend-color legend-range"></div>
                                <span>Selected Range</span>
                            </div>
                        </div>
                    </div>
                </div>
            </article>

            <!-- Add Date -->
            <aside class="card">
                <header class="card__h">
                    <h2 class="card__t">Add Availability</h2>
                </header>
                <div class="card__body">
                    <div class="alert alert--info">
                        Select a date range on the calendar to add availability for multiple days
                    </div>
                    
                    <div class="range-summary" id="range-summary" style="display: none;">
                        <h3>Selected Date Range</h3>
                        <p id="range-dates"></p>
                        <p id="range-count"></p>
                    </div>
                    
                    <form class="adddate" id="availability-form" method="POST" action="<?php echo URLROOT; ?>/Service/availability">
                        
                    
                        <div class="field">
                            <span class="field__label">Date Range</span>
                            <div class="time-inputs">
                                <input class="input" type="date" name="from-date" id="from-date" required>
                                <input class="input" type="date" name="to-date" id="to-date" required>
                            </div>
                        </div>

                        <div class="field">
                            <span class="field__label">Status</span>
                            <select class="input" id="status" name="status">
                                <option value="available">Available</option>
                                <option value="unavailable">Unavailable</option>
                            </select>
                        </div>

                        <div class="row-actions">
                            <button type="submit" class="btn btn--primary" id="add-availability">
                                <span>Mark Range as Available</span>
                            </button>
                            <button type="button" class="btn btn--light" id="view-events">
                                <span>View List</span>
                            </button>
                            <button type="button" class="btn btn--danger" id="clear-range">
                                <span>Clear Range</span>
                            </button>
                        </div>
                    </form>
                </div>
            </aside>
        </div>
    </div>

    <div class="tab-content" id="availability-tab">
        <div class="card">
            <header class="card__head">
                <h2 class="card__title">Current Availability</h2>
            </header>
            <div class="card__body">
                <table class="availability-table" id="availability-table">
                    <thead>
                        <tr>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Time Slot</th>
                            <th>Status</th>
                            <th>Service ID</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="availability-list">
                        <!-- Availability records will be populated here -->
                        

                        <?php foreach ($data['availability'] as $availability): ?>
                            <tr>
                                <td><?php echo date('Y-m-d', strtotime($availability->start_date)); ?></td>
                                <td><?php echo date('Y-m-d', strtotime($availability->end_date)); ?></td>
                                <td><?php echo $availability->timeslot; ?></td>
                                <td><?php echo ucfirst($availability->status); ?></td>
                                <td><?php echo $availability->service_id; ?></td>
                                <td>
                                    
                                    <button class="btn btn--danger delete-availability" data-id="<?php echo $availability->availability_id; ?>">
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>

                        <?php if (empty($data['availability'])): ?>
                            <tr>
                                <td colspan="5" style="text-align: center;">
                                    No availability records found. Add your first availability slot using the calendar view.
                                </td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
                <div class="empty-state" id="empty-state"></div>
                   
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Date Details Modal -->
<div class="modal" id="date-modal">
    <div class="modal__content">
        <div class="modal__header">
            <h2 class="modal__title" id="modal-date">Date Details</h2>
            <button class="modal__close" id="modal-close">&times;</button>
        </div>
        <div class="modal__body">
            <div class="date-info">
                <h3>Availability Slots</h3>
                <ul class="slot-list" id="slot-list">
                    <!-- Time slots will be populated here -->
                </ul>
            </div>
            <div class="field">
                <span class="field__label">Add Time Slot</span>
                <div class="time-inputs">
                    <input class="input" type="time" id="modal-start-time">
                    <input class="input" type="time" id="modal-end-time">
                </div>
            </div>
        </div>
        <div class="modal__footer">
            <button class="btn btn--light" id="modal-cancel">Cancel</button>
            <button class="btn btn--primary" id="modal-add">Add Slot</button>
        </div>
    </div>
</div>

<script>
    // Make PHP data available to JavaScript
    const URLROOT = '<?php echo URLROOT; ?>';
    const serverAvailabilityData = <?php echo json_encode($data['availability'] ?? []); ?>;
    
</script>


<!-- JavaScript -->
<script src="<?php echo URLROOT; ?>/js/calendar/availability.js"></script>

<?php require_once APPROOT . '/views/inc/footer.php'; ?>